# Generated by Django 4.0.6 on 2024-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisticName', models.CharField(max_length=30)),
                ('bandName', models.CharField(max_length=30)),
            ],
        ),
    ]
