# Generated by Django 4.0.6 on 2024-04-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_rename_areacientifica_area_cientifica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='curso.disciplina'),
        ),
    ]
