# Generated by Django 4.0.6 on 2024-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_projeto_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='linguagemProgramacao',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
